# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperformancetest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdokeriitk.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_abc4989c062d46c392ad4a12e16e0ec6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0e81dd1e9964a65a1107fad530c5256 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdokeriitk.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abc4989c062d46c392ad4a12e16e0ec6 }}/studentperformance1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformancetest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f483554b551e44998fedee313094e5f7 }}
        images: 'testdokeriitk.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_abc4989c062d46c392ad4a12e16e0ec6 }}/studentperformance1:${{ github.sha }}'